version: '3.8'
services:
  innoscripta-case-server:
    build:
      context: .
    image: kasia-server
    container_name: kasia-server
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27018/kasia
    networks:
      - all-apps

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: kasia
    volumes:
      - mongo-data:/data/db
    networks:
      - all-apps

networks:
  all-apps:
    external: true

volumes:
  mongo-data:
    external: false
